services:
  db_postgre:
    image: 'postgres:14.5-bullseye'
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-postgre-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: 'dpage/pgadmin4:5.5'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  db-postgre-data:
  pgadmin-data:
