services:
  db:
    image: 'mcr.microsoft.com/azure-sql-edge:latest'
    container_name: mssql
    volumes:
      - ./setup.sql:/usr/config/setup.sql
      - "db_mssql_statistics:/var/opt/mssql-extensibility"
      - "db_mssql_statistics_data:/var/opt/mssql-extensibility/data"     
      - "db_mssql_statistics_log:/var/opt/mssql-extensibility/log"
    ports:
      - 9933:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${ADMIN_PASSWORD}
      - MSSQL_PID=Developer
      - MSSQL_DB=price_stat
      - MSSQL_USER=${USER_LOGIN}
      - MSSQL_PASSWORD=${USER_PASSWORD}
volumes:
  db_mssql_statistics:
  db_mssql_statistics_data:
  db_mssql_statistics_log:
