services:
  db:
    image: 'mcr.microsoft.com/azure-sql-edge:latest'
    container_name: mssql
    volumes:
      - ./setup.sql:/usr/config/setup.sql
    ports:
      - 9933:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${ADMIN_PASSWORD}
      - MSSQL_PID=Developer
      - MSSQL_DB=price_stat
      - MSSQL_USER=${USER_LOGIN}
      - MSSQL_PASSWORD=${USER_PASSWORD}
  
